#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "News digest — OpenRouter deployment"

# ── Stage 1: Resend API key ──────────────────────────────────────────────
stage "Resend API key"
say "Digest emails are sent through Resend. We need your account API key."
open_url "https://resend.com/api-keys"
step "Sign in, then create or reveal an API key (value starts with re_)."
ask_secret RESEND_API_KEY "Paste the Resend API key:"
write_env RESEND_API_KEY "$RESEND_API_KEY"
set_secret RESEND_API_KEY "$RESEND_API_KEY"

# ── Stage 2: digest recipient ────────────────────────────────────────────
stage "Digest recipient email"
say "Each digest is emailed to this address (stored as RECIPIENT_EMAIL)."
ask RECIPIENT_EMAIL "Digest recipient email:"
write_env RECIPIENT_EMAIL "$RECIPIENT_EMAIL"
set_secret RECIPIENT_EMAIL "$RECIPIENT_EMAIL"

# ── Stage 3: OpenRouter API key ──────────────────────────────────────────
stage "OpenRouter API key"
say "Curation now runs through the OpenRouter chat-completions API with a"
say "bearer key; the model is pinned (currently z-ai/glm-5.3-flash)."
say "Written to .env (local runs) AND set as a GitHub secret (CI)."
open_url "https://openrouter.ai/settings/keys"
step "Sign in to OpenRouter, then create a key (value starts with sk-or-v1-)."
step "New account? Add credits first: openrouter.ai → Billing."
ask_secret OPENROUTER_API_KEY "Paste the OpenRouter API key:"
write_env OPENROUTER_API_KEY "$OPENROUTER_API_KEY"
set_secret OPENROUTER_API_KEY "$OPENROUTER_API_KEY"

# ── Stage 4: pinned curation model (optional) ─────────────────────────────
stage "Curation model (optional)"
say "The curation model is pinned. Leave it blank to keep the default"
say "z-ai/glm-5.3-flash (config.OPENROUTER_MODEL)."
ask OPENROUTER_MODEL "Pinned model id [Enter = z-ai/glm-5.3-flash]:"
if [[ -n "$OPENROUTER_MODEL" ]]; then
  write_env OPENROUTER_MODEL "$OPENROUTER_MODEL"
  set_var OPENROUTER_MODEL "$OPENROUTER_MODEL"
else
  note "kept default z-ai/glm-5.3-flash"
fi

# ── Stage 5: push the CI wiring ──────────────────────────────────────────
stage "Deploy: push main"
say "Secrets are in place. Next, push the digest changes to CI."
step "This runs: git push origin main"
if confirm "Push main to origin now?"; then
  git push origin main
else
  SKIPPED+=("git push origin main")
fi

# ── Stage 6: trigger a manual run to verify ──────────────────────────────
stage "Verify: trigger a manual run"
say "Each category runs as its own workflow, staggered 30 minutes apart:"
say "  digest-ai-ml.yml          08:00 UTC"
say "  digest-tech.yml           08:30 UTC"
say "  digest-video-games.yml    09:00 UTC"
say "  digest-politics-news.yml  09:30 UTC"
if command -v gh >/dev/null 2>&1; then
  step "We can dispatch one category now via the gh CLI to verify end to end."
  if confirm "Dispatch 'Digest — Tech' (digest-tech.yml) now?"; then
    gh workflow run digest-tech.yml --repo jennymaeleidig/news-digest-agent
  else
    SKIPPED+=("gh workflow run digest-tech.yml")
  fi
else
  open_url "https://github.com/jennymaeleidig/news-digest-agent/actions"
  step "Open any 'Digest — <category>' workflow → Run workflow → Run workflow."
fi
say "When it finishes, check data/run_log.jsonl: the row should show"
say "curate_error: null, a non-empty digest (or a clean empty digest), and a"
say "populated 'model' field equal to the pinned model id (z-ai/glm-5.3-flash)."
say "The other three workflows fire on their own crons; dispatch each manually"
say "from the Actions tab if you want to verify all four today."
pause "Press Enter once you've queued the run."

finish
